### ISSUE TITLE
JSON deserialization for type 'Claudia.ErrorResponseShape' was missing required properties, including the following: type

### ISSUE THREAD

**Issue by DUWENINK** [Cysharp/Claudia#8]
I use it with Net8.0  and deploy it in Ubuntu22.04,and I try the Demo Code,It reports `JSON deserialization for type 'Claudia.ErrorResponseShape' was missing required properties, including the following: type` Exception, But it is run ok in my dev env

**Comment by neuecc** [comment]
Thanks, I'll give it a try.
But if possible, I would like to know the specific JSON in case of an error.

**Comment by DUWENINK** [comment]
> Thanks, I'll give it a try. But if possible, I would like to know the specific JSON in case of an error.

Sorry about thant ,i change my network setting ,it ok,  it does'nt work with GFW

**Comment by neuecc** [comment]
OK.
However, regarding the error message when JSON deserialization fails, I will make it output a more user-friendly one!
